#!/bin/bash
#PBS -N runwrf
#PBS -A UOKL0041
#PBS -l walltime=00:10:00
#PBS -q main
#PBS -j oe
#PBS -k eod
### Select n nodes with a max of 128 CPUs per node for a total of n*128 MPI processes
#PBS -l select=3:ncpus=128:mpiprocs=128:ompthreads=1

# export TMPDIR=/glade/derecho/scratch/$USER/temp
# mkdir -p $TMPDIR

/bin/cp ../../bashrc_wrf_der bashrc_wrf
source bashrc_wrf

### Run the executable
mpiexec ./wrf.exe
