#!/bin/bash
#PBS -N runreal
#PBS -A UOKL0041
#PBS -l walltime=01:00:00
#PBS -q main
#PBS -j oe
#PBS -k eod
### Select n nodes with 64 CPUs each for a total of n*64 MPI processes
#PBS -l select=1:ncpus=64:mpiprocs=64:ompthreads=1

# export TMPDIR=/glade/derecho/scratch/$USER/temp
# mkdir -p $TMPDIR

/bin/cp ../../bashrc_wrf_der bashrc_wrf
source bashrc_wrf

### Run the executable
mpiexec ./real.exe
