#!/bin/bash
#PBS -N runreal
#PBS -A UFSU0031
#PBS -l walltime=01:30:00
#PBS -q main
#PBS -j oe
#PBS -k eod
### Select n nodes with a max of 128 CPUs per node for a total of n*128 MPI processes
#PBS -l select=5:ncpus=128:mpiprocs=128:ompthreads=1

#export TEMPDIR=/glade/derecho/scratch/$USER/piccolo/run4
#mkdir -p $TEMPDIR

/bin/cp ../../bashrc_wrf_der bashrc_wrf
source bashrc_wrf

#export RUNDIR=`pwd`
#cp -rafL $RUNDIR/* $TEMPDIR
#cd $TEMPDIR

#### Run the executable
mpiexec ./real.exe

